---
Name: commerceconfig
---
# Config overwrites
Checkout:
    simple_checkout: false
# Extensions
Controller:
  extensions:
    - CommerceControllerExtension
PaymentHandler:
  extensions:
    - CommercePaymentHandlerExtension
SiteConfig:
  extensions:
    - CommerceSiteConfigExtension
OrderItem:
  extensions:
    - CommerceOrderItem
CatalogueProductController:
  extensions:
    - CommerceCatalogueProductControllerExtension
CatalogueProduct:
  extensions:
    - CommerceCatalogueProductExtension
